/* ============================================================
   THE LAYERING LAB — FRAGRANCE DATABASE
   Edit THIS file to add fragrances. The app reads from it.
   families: citrus, fresh, aromatic, fruity, floral, gourmand,
             amber, spicy, woody, leather, smoky, musky, boozy, powdery
   ============================================================ */
const FRAGS=[
/* ---- designer pillars ---- */
{id:'bdc',name:'Bleu de Chanel EDP',house:'Chanel',fam:['citrus','woody','aromatic'],top:['grapefruit','lemon','mint'],heart:['ginger','incense'],base:['cedar','sandalwood','amber'],season:'Year-round',vibe:'polished blue'},
{id:'sauvage',name:'Sauvage EDP',house:'Dior',fam:['fresh','spicy','amber'],top:['bergamot'],heart:['lavender','star anise','nutmeg'],base:['ambroxan','vanilla'],season:'Year-round',vibe:'mass-appeal fresh-spicy'},
{id:'elixir',name:'Sauvage Elixir',house:'Dior',fam:['spicy','aromatic','boozy'],top:['cinnamon','nutmeg','grapefruit'],heart:['lavender','licorice'],base:['amber','patchouli','vetiver'],season:'Fall–Winter',vibe:'concentrated spiced power'},
{id:'eros',name:'Eros EDT',house:'Versace',fam:['fresh','gourmand','aromatic'],top:['mint','green apple','lemon'],heart:['tonka','geranium'],base:['vanilla','vetiver','oakmoss'],season:'Year-round',vibe:'minty vanilla flex'},
{id:'erosflame',name:'Eros Flame',house:'Versace',fam:['fruity','spicy','woody'],top:['black pepper','lemon','orange'],heart:['rose','geranium'],base:['vanilla','tonka','sandalwood'],season:'Fall–Winter',vibe:'peppery rose-vanilla'},
{id:'dylanblue',name:'Dylan Blue',house:'Versace',fam:['aromatic','woody','fresh'],top:['bergamot','grapefruit'],heart:['violet leaf','papyrus'],base:['musk','tonka','saffron'],season:'Year-round',vibe:'aquatic woody'},
{id:'profondo',name:'Acqua di Giò Profondo',house:'Giorgio Armani',fam:['fresh','musky','aromatic'],top:['marine notes','bergamot'],heart:['rosemary','lavender'],base:['mineral musk','patchouli'],season:'Spring–Summer',vibe:'deep-sea clean'},
{id:'stronger',name:'Stronger With You Intensely',house:'Emporio Armani',fam:['gourmand','spicy','amber'],top:['pink pepper','juniper'],heart:['toffee','lavender'],base:['vanilla','tonka','amber'],season:'Fall–Winter',vibe:'toffee date-night'},
{id:'yedp',name:'Y EDP',house:'Yves Saint Laurent',fam:['fresh','fruity','woody'],top:['apple','ginger','bergamot'],heart:['sage','geranium'],base:['amberwood','tonka','cedar'],season:'Year-round',vibe:'clean apple-woods'},
{id:'myslf',name:'MYSLF EDP',house:'Yves Saint Laurent',fam:['floral','woody','musky'],top:['bergamot'],heart:['orange blossom'],base:['ambroxan','patchouli','woods'],season:'Spring–Fall',vibe:'modern clean floral'},
{id:'lanuit',name:'La Nuit de L\u2019Homme',house:'Yves Saint Laurent',fam:['spicy','aromatic','woody'],top:['cardamom','bergamot'],heart:['lavender','cedar'],base:['vetiver','coumarin'],season:'Year-round',vibe:'seductive cardamom'},
{id:'lme',name:'Le Male Elixir',house:'Jean Paul Gaultier',fam:['gourmand','aromatic','boozy'],top:['lavender','mint'],heart:['vanilla','benzoin'],base:['honey','tobacco','tonka'],season:'Fall–Winter',vibe:'honeyed tobacco-vanilla'},
{id:'lemale',name:'Le Male EDT',house:'Jean Paul Gaultier',fam:['aromatic','gourmand','floral'],top:['mint','lavender','bergamot'],heart:['cinnamon','orange blossom'],base:['vanilla','tonka','sandalwood'],season:'Year-round',vibe:'minty barbershop vanilla'},
{id:'ultramale',name:'Ultra Male',house:'Jean Paul Gaultier',fam:['fruity','gourmand','aromatic'],top:['pear','mint','bergamot'],heart:['lavender','cinnamon'],base:['vanilla','amber','tonka'],season:'Fall–Winter',vibe:'juicy pear-vanilla beast'},
{id:'invictus',name:'Invictus',house:'Paco Rabanne',fam:['fresh','aromatic','woody'],top:['grapefruit','marine notes'],heart:['bay leaf','jasmine'],base:['guaiac wood','oakmoss','ambergris'],season:'Spring–Summer',vibe:'fresh gym-bro classic'},
{id:'1million',name:'1 Million',house:'Paco Rabanne',fam:['spicy','leather','gourmand'],top:['blood mandarin','grapefruit','mint'],heart:['cinnamon','rose','spices'],base:['leather','amber','patchouli'],season:'Fall–Winter',vibe:'cinnamon cash-money'},
{id:'phantom',name:'Phantom Parfum',house:'Paco Rabanne',fam:['aromatic','gourmand','woody'],top:['lavender','lemon'],heart:['smoky apple','lavender'],base:['vanilla','vetiver'],season:'Year-round',vibe:'sweet lavender tech'},
{id:'lhomme',name:'L\u2019Homme',house:'Prada',fam:['musky','floral','fresh'],top:['neroli','black pepper'],heart:['iris','geranium'],base:['amber','cedar','clean musk'],season:'Spring–Summer',vibe:'iris soap, ironed shirt'},
{id:'terre',name:'Terre d\u2019Herm\u00e8s',house:'Herm\u00e8s',fam:['citrus','woody','spicy'],top:['orange','grapefruit'],heart:['pepper','flint'],base:['vetiver','cedar','benzoin'],season:'Spring–Fall',vibe:'earthy orange-vetiver'},
{id:'bleudd',name:'Spicebomb Extreme',house:'Viktor & Rolf',fam:['spicy','gourmand','smoky'],top:['black pepper','saffron'],heart:['cinnamon','cumin'],base:['tobacco','vanilla'],season:'Winter',vibe:'spiced tobacco grenade'},
{id:'tmw',name:'The Most Wanted EDP',house:'Azzaro',fam:['spicy','amber','boozy'],top:['cardamom'],heart:['toffee','red liquor accord'],base:['amberwood','vanilla'],season:'Fall–Winter',vibe:'boozy caramel amber'},
{id:'wantedbynight',name:'Wanted by Night',house:'Azzaro',fam:['spicy','woody','amber'],top:['cinnamon','lemon'],heart:['cardamom','tobacco'],base:['cedar','vanilla','amber'],season:'Winter',vibe:'spicy woody seducer'},
{id:'boss',name:'Boss Bottled',house:'Hugo Boss',fam:['fruity','woody','spicy'],top:['apple','bergamot'],heart:['cinnamon','geranium'],base:['sandalwood','vanilla','vetiver'],season:'Year-round',vibe:'apple-cinnamon office staple'},
{id:'allure',name:'Allure Homme Sport',house:'Chanel',fam:['citrus','aromatic','woody'],top:['orange','sea notes','mandarin'],heart:['pepper','cedar'],base:['tonka','white musk','amber'],season:'Spring–Summer',vibe:'clean sporty citrus'},

/* ---- niche & high-end ---- */
{id:'aventus',name:'Aventus',house:'Creed',fam:['fruity','smoky','woody'],top:['pineapple','bergamot','blackcurrant'],heart:['birch','patchouli','rose'],base:['musk','oakmoss','vanilla'],season:'Spring–Fall',vibe:'smoky pineapple'},
{id:'viw',name:'Virgin Island Water',house:'Creed',fam:['citrus','fruity','boozy'],top:['lime','coconut','bergamot'],heart:['white rum','ginger','jasmine'],base:['sugar cane','musk'],season:'Summer',vibe:'coconut-lime rum'},
{id:'git',name:'Green Irish Tweed',house:'Creed',fam:['fresh','aromatic','woody'],top:['lemon','verbena'],heart:['violet leaf','iris'],base:['sandalwood','ambergris'],season:'Spring–Fall',vibe:'classic green gentleman'},
{id:'silvermountain',name:'Silver Mountain Water',house:'Creed',fam:['fresh','citrus','musky'],top:['bergamot','mandarin'],heart:['green tea','blackcurrant'],base:['musk','sandalwood','galbanum'],season:'Spring–Summer',vibe:'crisp tea-blackcurrant'},
{id:'br540',name:'Baccarat Rouge 540',house:'Maison Francis Kurkdjian',fam:['amber','gourmand','musky'],top:['saffron','jasmine'],heart:['amberwood','ambergris'],base:['fir resin','cedar'],season:'Fall–Winter',vibe:'sweet mineral glow'},
{id:'gs',name:'Grand Soir',house:'Maison Francis Kurkdjian',fam:['amber','gourmand','boozy'],top:['benzoin'],heart:['labdanum','amber'],base:['vanilla','tonka'],season:'Fall–Winter',vibe:'golden evening amber'},
{id:'oud540',name:'Oud Satin Mood',house:'Maison Francis Kurkdjian',fam:['amber','floral','woody'],top:['violet'],heart:['rose','oud'],base:['vanilla','benzoin'],season:'Winter',vibe:'plush rose-oud velvet'},
{id:'ol',name:'Ombr\u00e9 Leather',house:'Tom Ford',fam:['leather','amber','spicy'],top:['cardamom'],heart:['leather','jasmine sambac'],base:['amber','moss','patchouli'],season:'Fall–Winter',vibe:'desert leather'},
{id:'tv',name:'Tobacco Vanille',house:'Tom Ford',fam:['gourmand','smoky','spicy'],top:['tobacco leaf','spices'],heart:['vanilla','cacao','tonka'],base:['dried fruits','woods'],season:'Winter',vibe:'pipe-tobacco dessert'},
{id:'oudwood',name:'Oud Wood',house:'Tom Ford',fam:['woody','spicy','amber'],top:['oud','rosewood'],heart:['cardamom','sandalwood'],base:['vanilla','amber','tonka'],season:'Fall–Winter',vibe:'smooth approachable oud'},
{id:'tuscanleather',name:'Tuscan Leather',house:'Tom Ford',fam:['leather','fruity','smoky'],top:['raspberry','saffron'],heart:['leather','jasmine'],base:['suede','woods','amber'],season:'Fall–Winter',vibe:'raspberry suede'},
{id:'lostcherry',name:'Lost Cherry',house:'Tom Ford',fam:['fruity','gourmand','amber'],top:['black cherry','liqueur'],heart:['cherry blossom','almond'],base:['tonka','vanilla','sandalwood'],season:'Fall–Winter',vibe:'boozy cherry-almond'},
{id:'fuckingfabulous',name:'F***ing Fabulous',house:'Tom Ford',fam:['leather','aromatic','powdery'],top:['lavender','sage'],heart:['leather','orris'],base:['amber','tonka','vanilla'],season:'Fall–Winter',vibe:'almond-leather suede'},
{id:'s33',name:'Santal 33',house:'Le Labo',fam:['woody','leather','musky'],top:['cardamom','violet'],heart:['iris','sandalwood'],base:['leather','cedar','musk'],season:'Year-round',vibe:'dry desert sandalwood'},
{id:'another13',name:'Another 13',house:'Le Labo',fam:['musky','amber','woody'],top:['ambrette','pear'],heart:['ambroxan','jasmine'],base:['moss','musk','amber'],season:'Year-round',vibe:'clean skin musk'},
{id:'rose31',name:'Rose 31',house:'Le Labo',fam:['woody','floral','spicy'],top:['rose','cumin'],heart:['cedar','vetiver'],base:['oud','musk','guaiac'],season:'Year-round',vibe:'masculine spiced rose'},
{id:'layton',name:'Layton',house:'Parfums de Marly',fam:['fruity','gourmand','spicy'],top:['apple','bergamot','lavender'],heart:['geranium','violet','jasmine'],base:['vanilla','cardamom','guaiac wood'],season:'Fall–Winter',vibe:'regal apple-vanilla'},
{id:'pegasus',name:'Pegasus',house:'Parfums de Marly',fam:['gourmand','aromatic','musky'],top:['bergamot','heliotrope'],heart:['bitter almond','lavender'],base:['vanilla','sandalwood','amber'],season:'Fall–Winter',vibe:'almond-cream elegance'},
{id:'herod',name:'Herod',house:'Parfums de Marly',fam:['spicy','gourmand','smoky'],top:['cinnamon','pepper'],heart:['osmanthus','tobacco'],base:['vanilla','vetiver','incense'],season:'Winter',vibe:'cinnamon-tobacco warmth'},
{id:'kalan',name:'Kalan',house:'Parfums de Marly',fam:['boozy','spicy','amber'],top:['grapefruit','rum'],heart:['cardamom','geranium'],base:['amber','vanilla','tonka'],season:'Fall–Winter',vibe:'boozy spiced grapefruit'},
{id:'naxos',name:'Naxos',house:'Xerjoff',fam:['gourmand','smoky','aromatic'],top:['lavender','bergamot'],heart:['honey','cinnamon','jasmine'],base:['tobacco','vanilla','tonka'],season:'Fall–Winter',vibe:'honeyed Sicilian tobacco'},
{id:'erba',name:'Erba Pura',house:'Xerjoff',fam:['fruity','gourmand','amber'],top:['orange','lemon','bergamot'],heart:['fruity accord'],base:['white musk','amber','vanilla'],season:'Year-round',vibe:'juicy candied fruit'},
{id:'oudwood2',name:'Oud Wood Intense',house:'Tom Ford',fam:['woody','smoky','spicy'],top:['oud','pepper'],heart:['saffron','cedar'],base:['amber','incense','vanilla'],season:'Winter',vibe:'smokier oud'},

/* ---- popular gourmands / sweet ---- */
{id:'amorecaffe',name:'Amore Caff\u00e8',house:'Mancera',fam:['gourmand','boozy','musky'],top:['coffee','bergamot'],heart:['vanilla','jasmine'],base:['caramel','white musk','amber'],season:'Fall–Winter',vibe:'creamy coffee-vanilla'},
{id:'cedrataria',name:'Cedrat Boise',house:'Mancera',fam:['citrus','woody','fruity'],top:['lemon','bergamot'],heart:['apple','patchouli'],base:['sandalwood','musk','amber'],season:'Year-round',vibe:'sweet lemon-wood'},
{id:'rosevanille',name:'Roses Vanille',house:'Mancera',fam:['floral','gourmand','musky'],top:['lemon'],heart:['rose','milk'],base:['vanilla','white musk'],season:'Year-round',vibe:'creamy rose-vanilla'},
{id:'khamrah',name:'Khamrah',house:'Lattafa',fam:['boozy','gourmand','spicy'],top:['cinnamon','nutmeg','bergamot'],heart:['dates','praline','tuberose'],base:['vanilla','tonka','benzoin'],season:'Winter',vibe:'spiced whiskey dessert'},
{id:'asadoftears',name:'Asad',house:'Lattafa',fam:['woody','boozy','spicy'],top:['pineapple','black pepper'],heart:['violet','tobacco'],base:['vanilla','amberwood','cedar'],season:'Year-round',vibe:'aventus-adjacent sweet smoke'},
{id:'yara',name:'Yara',house:'Lattafa',fam:['fruity','gourmand','floral'],top:['orchid','heliotrope'],heart:['tropical fruits'],base:['vanilla','sandalwood','musk'],season:'Year-round',vibe:'creamy tropical sweet'},
{id:'cloud',name:'Cloud',house:'Ariana Grande',fam:['gourmand','musky','fruity'],top:['lavender','pear','bergamot'],heart:['whipped cream','coconut','praline'],base:['vanilla orchid','musk'],season:'Year-round',vibe:'fluffy sweet cream'},
{id:'goodgirl',name:'Good Girl',house:'Carolina Herrera',fam:['floral','gourmand','amber'],top:['almond','coffee'],heart:['tuberose','jasmine'],base:['tonka','cacao','vanilla'],season:'Fall–Winter',vibe:'almond-coffee femme'},
{id:'borntoroma',name:'Uomo Born in Roma',house:'Valentino',fam:['gourmand','spicy','woody'],top:['ginger','sage'],heart:['vanilla','salt'],base:['vetiver','woods'],season:'Year-round',vibe:'salty mineral vanilla'},
{id:'kirkeperfume',name:'Kirke',house:'Tiziana Terenzi',fam:['fruity','gourmand','musky'],top:['passion fruit','blackcurrant'],heart:['peach','musk'],base:['sandalwood','vanilla','amber'],season:'Year-round',vibe:'tropical passionfruit candy'},

/* ---- fresh / summer ---- */
{id:'lightblue',name:'Light Blue',house:'Dolce & Gabbana',fam:['citrus','fruity','woody'],top:['lemon','apple','bellflower'],heart:['bamboo','jasmine'],base:['cedar','musk','amber'],season:'Summer',vibe:'lemon-apple summer staple'},
{id:'kbyone',name:'K by Dolce',house:'Dolce & Gabbana',fam:['citrus','aromatic','woody'],top:['blood orange','juniper'],heart:['pimento','geranium'],base:['cedar','vetiver','patchouli'],season:'Year-round',vibe:'citrus-herb woody'},
{id:'megamare',name:'Megamare',house:'Orto Parisi',fam:['fresh','musky','smoky'],top:['marine accord'],heart:['ambergris','seaweed'],base:['musk','woods'],season:'Summer',vibe:'ocean at full volume'},
{id:'cdnim',name:'CDNIM',house:'Frederic Malle',fam:['fresh','musky','woody'],top:['bergamot','black pepper'],heart:['geranium','rose'],base:['ambrette','sandalwood','musk'],season:'Spring–Summer',vibe:'transparent musky elegance'},
{id:'colognefr',name:'Mojave Ghost',house:'Byredo',fam:['woody','floral','fresh'],top:['ambrette','sapodilla'],heart:['violet','magnolia'],base:['sandalwood','cedar','musk'],season:'Spring–Fall',vibe:'dry airy woods'},
{id:'gypsywater',name:'Gypsy Water',house:'Byredo',fam:['woody','aromatic','citrus'],top:['bergamot','lemon','pepper','juniper'],heart:['incense','pine','orris'],base:['amber','vanilla','sandalwood'],season:'Spring–Fall',vibe:'sweet woodsmoke'},

/* ---- women-leaning popular ---- */
{id:'blackopium',name:'Black Opium',house:'Yves Saint Laurent',fam:['gourmand','floral','aromatic'],top:['coffee','pear','pink pepper'],heart:['jasmine','orange blossom'],base:['vanilla','patchouli','cedar'],season:'Fall–Winter',vibe:'coffee-vanilla night out'},
{id:'lavieestbelle',name:'La Vie Est Belle',house:'Lanc\u00f4me',fam:['gourmand','floral','powdery'],top:['blackcurrant','pear'],heart:['iris','jasmine','orange blossom'],base:['praline','vanilla','patchouli'],season:'Year-round',vibe:'sweet iris-praline'},
{id:'flowerbomb',name:'Flowerbomb',house:'Viktor & Rolf',fam:['floral','gourmand','amber'],top:['bergamot','tea','osmanthus'],heart:['jasmine','rose','orchid'],base:['patchouli','vanilla','musk'],season:'Fall–Winter',vibe:'explosive sweet floral'},
{id:'delina',name:'Delina',house:'Parfums de Marly',fam:['floral','fruity','powdery'],top:['lychee','rhubarb','bergamot'],heart:['turkish rose','peony'],base:['vanilla','musk','cashmeran'],season:'Year-round',vibe:'lychee-rose femme'},
{id:'bdcrose',name:'Mon Guerlain',house:'Guerlain',fam:['gourmand','floral','aromatic'],top:['bergamot','lavender'],heart:['jasmine','iris'],base:['vanilla','sandalwood','coumarin'],season:'Year-round',vibe:'lavender-vanilla soft'},
{id:'libre',name:'Libre',house:'Yves Saint Laurent',fam:['floral','aromatic','amber'],top:['lavender','mandarin'],heart:['orange blossom','jasmine'],base:['vanilla','musk','cedar'],season:'Year-round',vibe:'lavender-orange blossom'},
{id:'idole',name:'Id\u00f4le',house:'Lanc\u00f4me',fam:['floral','musky','citrus'],top:['bergamot','pear'],heart:['rose','jasmine'],base:['white musk','vanilla'],season:'Spring–Summer',vibe:'clean fresh rose'},

/* ---- more common designer / mass-popular ---- */
{id:'sauvageedt',name:'Sauvage EDT',house:'Dior',fam:['fresh','aromatic','woody'],top:['bergamot','pepper'],heart:['lavender','sichuan pepper','geranium'],base:['ambroxan','cedar','labdanum'],season:'Spring–Summer',vibe:'fresher original Sauvage'},
{id:'hommeintense',name:'Dior Homme Intense',house:'Dior',fam:['powdery','floral','woody'],top:['lavender'],heart:['iris','ambrette','pear'],base:['vetiver','cedar','virginia cedar'],season:'Fall–Winter',vibe:'powdery iris elegance'},
{id:'fahrenheit',name:'Fahrenheit',house:'Dior',fam:['woody','aromatic','floral'],top:['mandarin','nutmeg'],heart:['violet','carnation','jasmine'],base:['leather','vetiver','sandalwood'],season:'Fall–Winter',vibe:'gasoline-violet classic'},
{id:'jpgscandal',name:'Scandal Pour Homme',house:'Jean Paul Gaultier',fam:['gourmand','aromatic','woody'],top:['blood orange','clary sage'],heart:['tonka','lavender'],base:['vetiver','caramel'],season:'Year-round',vibe:'caramel-sage charmer'},
{id:'bossnight',name:'Boss Bottled Night',house:'Hugo Boss',fam:['woody','aromatic','musky'],top:['lavender','birch'],heart:['cardamom','violet leaf'],base:['musk','sandalwood'],season:'Year-round',vibe:'dark woody office'},
{id:'coolwater',name:'Cool Water',house:'Davidoff',fam:['fresh','aromatic','woody'],top:['mint','lavender','sea notes'],heart:['geranium','sandalwood'],base:['musk','tobacco','oakmoss'],season:'Spring–Summer',vibe:'90s aquatic legend'},
{id:'nautica',name:'Nautica Voyage',house:'Nautica',fam:['fresh','fruity','woody'],top:['apple','lotus'],heart:['mimosa','lotus'],base:['cedar','musk','amber'],season:'Spring–Summer',vibe:'cheap fresh crowd-pleaser'},
{id:'blueseduction',name:'Blue Seduction',house:'Antonio Banderas',fam:['fresh','fruity','woody'],top:['mint','blackcurrant','melon'],heart:['cardamom','sage'],base:['musk','amber','cedar'],season:'Spring–Summer',vibe:'budget blue fresh'},
{id:'adgmen',name:'Acqua di Gi\u00f2 (original)',house:'Giorgio Armani',fam:['fresh','aromatic','citrus'],top:['bergamot','marine notes'],heart:['rosemary','jasmine'],base:['patchouli','cedar','musk'],season:'Spring–Summer',vibe:'iconic aquatic'},
{id:'codemen',name:'Armani Code',house:'Giorgio Armani',fam:['aromatic','gourmand','woody'],top:['bergamot','lemon'],heart:['orange blossom','star anise'],base:['tonka','leather','guaiac'],season:'Year-round',vibe:'tonka-anise seducer'},
{id:'gucciguilty',name:'Gucci Guilty',house:'Gucci',fam:['aromatic','citrus','amber'],top:['lemon','pink pepper'],heart:['lavender','orange blossom'],base:['patchouli','cedar','amber'],season:'Year-round',vibe:'lavender-citrus signature'},
{id:'theone',name:'The One for Men',house:'Dolce & Gabbana',fam:['spicy','amber','gourmand'],top:['grapefruit','coriander'],heart:['ginger','cardamom','orange blossom'],base:['tobacco','amber','cedar'],season:'Fall–Winter',vibe:'spicy tobacco warmth'},
{id:'intenso',name:'Intenso',house:'Dolce & Gabbana',fam:['aromatic','woody','gourmand'],top:['sage','lavender'],heart:['tobacco','geranium'],base:['labdanum','sandalwood','moss'],season:'Fall–Winter',vibe:'green tobacco depth'},
{id:'ckone',name:'CK One',house:'Calvin Klein',fam:['citrus','fresh','musky'],top:['bergamot','lemon','pineapple'],heart:['nutmeg','violet','rose'],base:['musk','amber','cedar'],season:'Spring–Summer',vibe:'classic clean unisex'},
{id:'jadore',name:'J\u2019adore',house:'Dior',fam:['floral','fruity','woody'],top:['pear','melon','bergamot'],heart:['jasmine','rose','orchid'],base:['musk','vanilla','blackcurrant'],season:'Year-round',vibe:'luminous floral femme'},
{id:'coco',name:'Coco Mademoiselle',house:'Chanel',fam:['floral','citrus','woody'],top:['orange','bergamot'],heart:['rose','jasmine','lychee'],base:['patchouli','vetiver','vanilla'],season:'Year-round',vibe:'elegant orange-patchouli'},
{id:'chanceeau',name:'Chance Eau Tendre',house:'Chanel',fam:['fruity','floral','musky'],top:['grapefruit','quince'],heart:['jasmine','hyacinth'],base:['white musk','amber','iris'],season:'Spring–Summer',vibe:'soft fruity-floral'},
{id:'narciso',name:'Narciso Rodriguez For Her',house:'Narciso Rodriguez',fam:['musky','floral','woody'],top:['rose','peach'],heart:['musk','amber','orange blossom'],base:['vetiver','vanilla','patchouli'],season:'Year-round',vibe:'sultry musk signature'},
{id:'siarmani',name:'Si',house:'Giorgio Armani',fam:['fruity','floral','woody'],top:['blackcurrant','bergamot'],heart:['rose','freesia'],base:['vanilla','patchouli','amber'],season:'Year-round',vibe:'blackcurrant chypre femme'},
{id:'br540extrait',name:'Baccarat Rouge 540 Extrait',house:'Maison Francis Kurkdjian',fam:['amber','gourmand','woody'],top:['saffron','bitter almond'],heart:['cedar','amberwood'],base:['oakmoss','woods'],season:'Fall–Winter',vibe:'deeper smokier BR540'},
{id:'aqua',name:'Aqua Universalis',house:'Maison Francis Kurkdjian',fam:['citrus','fresh','musky'],top:['bergamot','lemon'],heart:['lily of the valley'],base:['white musk','woods'],season:'Spring–Summer',vibe:'clean fresh-laundry'},
{id:'angelsshare',name:'Angels\u2019 Share',house:'Kilian',fam:['boozy','gourmand','woody'],top:['cognac'],heart:['cinnamon','tonka'],base:['vanilla','sandalwood','praline'],season:'Winter',vibe:'cognac-cinnamon dessert'},
{id:'badboy',name:'Bad Boy',house:'Carolina Herrera',fam:['spicy','gourmand','woody'],top:['black pepper','bergamot'],heart:['sage','cinnamon'],base:['tonka','cacao','amber'],season:'Fall–Winter',vibe:'cacao-pepper electric'},
{id:'212vip',name:'212 VIP Men',house:'Carolina Herrera',fam:['boozy','gourmand','spicy'],top:['lime'],heart:['ginger','black pepper'],base:['amber','leather','tonka'],season:'Year-round',vibe:'party vodka-lime'},
{id:'invictusvic',name:'Invictus Victory',house:'Paco Rabanne',fam:['woody','spicy','amber'],top:['bergamot','sage'],heart:['cypress','myrrh'],base:['amber','oud','vanilla'],season:'Fall–Winter',vibe:'premium spicy-woody'}
];
if(typeof module!=='undefined') module.exports={FRAGS};
